"use client";

// import { Inter } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'
import './globals.css'
import { Box, Container, Divider, Sheet, Typography } from '@mui/joy'
import ThemeRegistry from './ThemeRegistry';
import Link from 'next/link';

import packageJson from '../package.json';

// const inter = Inter({ subsets: ['latin'] })
const ibmPlexSans = IBM_Plex_Sans({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700']
})

export const metadata = {
    title: 'BehandlerPaycheck',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="da" style={{ height: '100%' }}>
            <ThemeRegistry options={{ key: 'mui' }}>
                {/* <body className={ibmPlexSans.className}> */}
                <body style={{ height: '90%' }}>
                    <nav>
                        <Container>
                            <Link href='/'>
                                <Typography level='h2' py={3}>
                                    BehandlerPaycheck
                                </Typography>
                            </Link>
                        </Container>
                    </nav>
                    <main style={{ minHeight: '100%' }}>
                        {children}
                    </main>
                    <footer>
                        {/* <Container> */}
                            <Divider />
                            {/* <Sheet variant='soft'> */}
                                <Box p={1}>
                                    <Box sx={{ display: 'flex', direction: 'row', alignItems: 'center', gap: 3 }}>
                                        {/* <Link href='/'>
                                            <Typography level='h4'>
                                                BehandlerPaycheck
                                            </Typography>
                                        </Link> */}
                                        <Typography>
                                            v{packageJson.version}
                                        </Typography>
                                        <Typography level='body-md'>
                                            Side af Oliver Christensen
                                        </Typography>
                                        <Link href='mailto:orc-developer@outlook.com'>
                                            <Typography level='body-md'>
                                                Kontakt
                                            </Typography>
                                        </Link>
                                    </Box>
                                </Box>
                            {/* </Sheet> */}
                        {/* </Container> */}
                    </footer>
                </body>
            </ThemeRegistry>
        </html>
    )
}
