"use client"

// import { Inter } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript, createTheme } from '@mantine/core';
import './globals.css'
import packageJson from '../package.json';

// const inter = Inter({ subsets: ['latin'] })
const ibmPlexSans = IBM_Plex_Sans({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700']
})

export const metadata = {
    title: 'BehandlerPaycheck',
    description: 'Generated by create next app',
}

const palePurpleColors = [
    "#f2f0ff",
    "#e0dff2",
    "#bfbdde",
    "#9b98ca",
    "#7d79ba",
    "#6a65b0",
    "#605bac",
    "#504c97",
    "#464388",
    "#3b3979"
];

const theme = createTheme({
    fontFamily: 'IBM Plex Sans, sans-serif',
    primaryColor: 'pale-purple',
    colors: {
        'pale-purple': palePurpleColors,
    },
    defaultRadius: 'md',
});

export default function RootLayout({ children }) {
    return (
        <html lang="da" style={{ height: '100%' }}>
            <head>
                <ColorSchemeScript />
            </head>
            {/* <body className={ibmPlexSans.className}> */}
            <body style={{ height: '100%' }}>
                <MantineProvider theme={theme}>
                    <main style={{ height: '100%' }}>
                        {children}
                    </main>
                </MantineProvider>
            </body>
        </html>
    )
}
