"use client"

// import { Inter } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'
import { Plus_Jakarta_Sans } from 'next/font/google';
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript, createTheme, Button, ActionIcon, Select } from '@mantine/core';
import './globals.css'
import packageJson from '../package.json';
import { ModalsProvider } from '@mantine/modals';

// const inter = Inter({ subsets: ['latin'] })
const ibmPlexSans = IBM_Plex_Sans({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700']
})

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

// export const metadata = {
//     title: 'BehandlerPaycheck',
//     description: 'Generated by create next app',
// }

const palePurpleColors = [
    "#f2f0ff",
    "#e0dff2",
    "#bfbdde",
    "#9b98ca",
    "#7d79ba",
    "#6a65b0",
    "#605bac",
    "#504c97",
    "#464388",
    "#3b3979"
];

const theme = createTheme({
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    primaryColor: 'pale-purple',
    colors: {
        'pale-purple': palePurpleColors,
    },
    defaultRadius: '0.85rem',
    components: {
        Button: Button.extend({
            defaultProps: {
                size: 'md',
                style: {
                    letterSpacing: 0.9,
                    fontWeight: 'bold',
                    // textTransform: 'uppercase'
                }
            },
        }),
        ActionIcon: ActionIcon.extend({
            defaultProps: {
                size: 'md',
                radius: 'md'
            },
        }),
        Select: Select.extend({
            defaultProps: {
                size: 'md',
                radius: 'md'
            },
        })
    },
});

export default function RootLayout({ children }) {
    return (
        <html lang="da" style={{ height: '100%' }}>
            <head>
                <title>BehandlerPaycheck</title>
                <ColorSchemeScript />
            </head>
            {/* <body className={plusJakartaSans.className} style={{ height: '100%' }}> */}
            <body className={ibmPlexSans.className} style={{ height: '100%' }}>
                {/* <body style={{ height: '100%' }}> */}
                <MantineProvider theme={theme} defaultColorScheme="light">
                    <ModalsProvider>
                        {children}
                    </ModalsProvider>
                </MantineProvider>
            </body>
        </html>
    )
}
